name: Node CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g pnpm
      - run: pnpm ci
      - run: pnpm build
